# code: language=ansible
---
- name: Remove api database
  become_user: postgres
  community.postgresql.postgresql_db:
   name: "{{ api_postgres_db }}"
   state: absent


- name: Remove api database user
  become_user: postgres
  community.postgresql.postgresql_user:
   name: "{{ api_postgres_user }}"
   state: absent
