# code: language=ansible
---
- name: Install postgresql
  when: install_postgres == 'true'
  community.general.zypper:
   name:
    - postgresql
    - postgresql-server
    - postgresql-server-devel
    - postgresql-contrib
   state: present
   update_cache: true

- name: Install postgres python management deps
  ansible.builtin.pip:
   name:
    - psycopg2-binary
   state: present

- name: Start postgresql service
  ansible.builtin.service:
   name: postgresql
   state: started
   enabled: true

- name: "Configure postgres to listen on *"
  become_user: postgres
  community.postgresql.postgresql_set:
   name: listen_addresses
   value: "*"
  notify: Restart postgres

- name: Configure pg_hba to accept connection from containers
  become_user: postgres
  notify: Restart postgres
  community.postgresql.postgresql_pg_hba:
   contype: host
   dest: "/var/lib/pgsql/data/pg_hba.conf"
   databases: all
   users: all
   address: "0.0.0.0/0"
   method: "md5"

- name: Create postgres api database
  become_user: postgres
  community.postgresql.postgresql_db:
   name: "{{ api_postgres_db }}"
   state: present

- name: Create api database user
  become_user: postgres
  community.postgresql.postgresql_user:
   db: "{{ api_postgres_db }}"
   name: "{{ api_postgres_user }}"
   password: "{{ api_postgres_password }}"
   comment: "Api user provisioned by playbook"
   state: present

- name: Grant privilegies to the api user for the api database
  become_user: postgres
  community.postgresql.postgresql_privs:
   db: "{{ api_postgres_db }}"
   objs: public
   roles: "{{ api_postgres_user }}"
   privs: ALL
   type: schema
   state: present