# code: language=ansible
---
- name: Stop api container
  community.docker.docker_container:
    name: "{{api_container_name }}"
    state: absent
    keep_volumes: false

- name: Remove api container image
  when: remove_api_container_image == 'true'
  community.docker.docker_image:
    state: absent
    name: "{{ api_container_image }}"

- name: Remove docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: absent
    force: true
