# https://taskfile.dev

version: '3'

tasks:
  run-server:
    vars:
      PG_CONNECTION: "postgresql://postgres:postgres@localhost:5433/api_demo?sslmode=disable"
    cmds:
      - DB_CONNECTION={{ .PG_CONNECTION }} go run cmd/server/main.go
  migrate-down:
    cmds:
      - migrate -path internal/persistence/migrations -database "postgresql://postgres:postgres@localhost:5433/api_demo?sslmode=disable" down
 
  migrate-up:
    cmds:
      - migrate -path internal/persistence/migrations -database "postgresql://postgres:postgres@localhost:5433/api_demo?sslmode=disable" up

