name: Pull request environment cleanup

on:
  pull_request:
    types:
      - closed

env:
  PR_ENV_LABEL: env
  PR_NUMBER: "${{ github.event.pull_request.number }}"

jobs:
  check_env_creation_privilege:
    name: Check if the environment deletion criteria are met, store in the job output
    runs-on: ubuntu-latest
    outputs:
      create_env: ${{ steps.check.outputs.create_env }}
    steps:
      - id: check
        run: echo "create_env=${{ contains(github.event.pull_request.labels.*.name, env.PR_ENV_LABEL) }}" >> "$GITHUB_OUTPUT"

  delete-pr-image:
    needs: check_env_creation_privilege
    name: Build and push pull request container image
    runs-on: ubuntu-latest
    if: needs.check_env_creation_privilege.outputs.create_env == 'true'
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_TAG: ${{ github.event.pull_request.number }}-env
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete the container image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: cdimonaco
          name: pr-api
          tag: ${{ env.IMAGE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}